execution_env=local
#execution_env=remote

appURL=https://tutorialsninja.com/demo/
email = kasazy@mailinator.com
password = 123123Sd@

email1 = mukodybybe@mailinator.com
email2 = hyry@mailinator.com

searchProductName = iphone